plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.175'
    id 'java'
}

version = "1.1.6-hotfix"
group = "com.tacz"
archivesBaseName = "tacz-1.21.1"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
}

jar {
    manifest {
        attributes([
                "Implementation-Title"  : project.name,
                "Implementation-Version": project.version
        ])
    }
}

java {
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
