modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mixins]]
config = "tacz.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
updateJSONURL = ""
displayURL = ""
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "shouldersurfing"
mandatory = false
versionRange = "[1.21.1-4.0.0,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.tacz]
catalogueItemIcon = "tacz:gun_smith_table"