#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 16 18:57:24 BRT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
